# Generated by Django 4.2.7 on 2023-11-11 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_todo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user',
            new_name='userId',
        ),
    ]
